## Hopfield Modell

zunächst werdenen die benötigten Bibliotheken implementiert

In [3]:
import numpy as np
import cv2
import matplotlib.pyplot as plt
import matplotlib
matplotlib.use('MacOSX')

Jetzt wird zunächst das Hopfieldmodel implementiert

In [6]:

class HopfieldNetwork:
    
    #Initierungsfunktion
    def __init__(self, num_neurons, steps):
        self.num_neurons = num_neurons
        self.matrix_size = int(np.sqrt(self.num_neurons))
        self.weights = np.zeros((num_neurons, num_neurons))
        self.steps = steps
    #Trainig durch die Hebbsche Regel. Normiert auf die Anzahl der Neuronen. Input sind gegebene Patterns
    def train(self, patterns):
        for p in patterns:
            print(p)
            p = p.flatten()  # Ensuring pattern is a column vector
            print(p)
            self.weights += np.outer(p, p)
        self.weights /= self.num_neurons
        np.fill_diagonal(self.weights, 0)  # No self-connections
        

    def show_as_matrix(self,pattern):
        matrix = np.reshape(pattern, (self.matrix_size, self.matrix_size))
        return matrix

    def predict(self, pattern, activation_function, number_of_pattern = None, axs = None):
        s = pattern.copy().reshape(-1, 1)  # Kopie des Musters und Umformung zu Spaltenvektor
        for i in range(self.steps):
            s = np.dot(self.weights, s)
            s = activation_function(s)
            if number_of_pattern and axs is not None:
                axs[1,i].imshow(self.show_as_matrix(s.flatten()))
                axs[1,i].set_title(f'Nach {i+1} Steps')
        return s.flatten()  # Rückgabe als flaches Array
    

    def energy(self, pattern):
       
        return -0.5 * np.dot(np.dot(pattern.T, self.weights), pattern)
    
def tanh(a):
    return np.tanh(a)
    
def heviside(a):
    return np.where(a >= 0, 1, -1)


In [2]:
# Beispielmuster
patterns = [np.array([1, -1, 1, -1]), np.array([-1, 1, 1, -1])]

# Hopfield-Netzwerk mit 4 Neuronen initialisieren
network = HopfieldNetwork(num_neurons=4, steps= 5)

# Netzwerk mit den Mustern trainieren
network.train(patterns)

# Vorhersage für ein verrauschtes Muster
test_pattern = np.array([-1, -1, 1, -1])
result = network.predict(test_pattern, heviside)

print("Ursprüngliches Muster:", test_pattern)
print("Erkanntes Muster:", result)
print("Energie des erkannten Musters:", network.energy(result))
matrix_result = network.show_as_matrix(result)
print(matrix_result)
plt.imshow(network.show_as_matrix(patterns[0]), cmap='gray', interpolation='none')
plt.show()
plt.imshow(network.show_as_matrix(patterns[1]), cmap='gray', interpolation='none')
plt.show()
plt.imshow(network.show_as_matrix(test_pattern), cmap='gray', interpolation='none')
plt.show()
plt.imshow(matrix_result, cmap='gray', interpolation='none')
plt.show()


NameError: name 'np' is not defined

In [17]:
# Beispielmuster
patterns = [
    np.array([
        [1, 1, 1, 1, 1],
        [1, -1, 1, -1, 1],
        [1, 1, 1, 1, 1],
        [-1, 1, 1, 1, -1],
        [1, -1, -1, -1, 1]
    ]),
    np.array([
        [1, 1, 1, 1, 1],
        [1, -1, 1, -1, 1],
        [1, 1, 1, 1, 1],
        [1, -1, -1, -1, 1],
        [-1, 1, 1, 1, -1]
    ]),
    np.array([
        [1, 1, -1, 1, 1],
        [1, 1, -1, 1, 1],
        [1, 1, -1, 1, 1],
        [1, -1, 1, -1, 1],
        [-1, -1, 1, -1, -1]
    ])
]

# Hopfield-Netzwerk mit Neuronen initialisieren
network = HopfieldNetwork(num_neurons=25, steps= 2)

# Netzwerk mit den Mustern trainieren
network.train(patterns)

# Vorhersage für ein verrauschtes Muster
test_pattern =[
    np.array([
        [1, 1, -1, 1, 1],
        [1, -1, -1, -1, 1],
        [1, 1, -1, 1, 1], #Misichzustand
        [1, 1, -1, -1, 1],
        [-1, -1, 1, 1, -1]
    ]),
    np.array([
        [1, 1, -1, 1, 1],
        [1, -1, -1, -1, 1],
        [1, 1, -1, 1, 1],
        [1, -1, -1, -1, 1],
        [-1, 1, 1, 1, -1]
    ]),
        np.array([
        [1, 1, -1, 1, 1],
        [1, -1, -1, -1, 1],
        [1, 1, -1, 1, 1], # konvergiert zu rakete in 2 schritten
        [1, -1, 1, -1, 1],
        [-1, -1, 1, -1, -1]
    ])
]



# Zu beobachtendes pattern auswählen:
view_patter = 1
result = network.predict(test_pattern[view_patter],heviside)

print("Ursprüngliches Muster:", test_pattern[view_patter])
print("Erkanntes Muster:", result)
print("Energie des erkannten Musters:", network.energy(result))
matrix_result = network.show_as_matrix(result)
plt.imshow(network.show_as_matrix(patterns[0]), cmap='gray', interpolation='none')
plt.show()
plt.imshow(network.show_as_matrix(test_pattern[view_patter]), cmap='gray', interpolation='none')
plt.show()
plt.imshow(matrix_result, cmap='gray', interpolation='none')
plt.show()


[[ 1  1  1  1  1]
 [ 1 -1  1 -1  1]
 [ 1  1  1  1  1]
 [-1  1  1  1 -1]
 [ 1 -1 -1 -1  1]]
[ 1  1  1  1  1  1 -1  1 -1  1  1  1  1  1  1 -1  1  1  1 -1  1 -1 -1 -1
  1]
[[ 1  1  1  1  1]
 [ 1 -1  1 -1  1]
 [ 1  1  1  1  1]
 [ 1 -1 -1 -1  1]
 [-1  1  1  1 -1]]
[ 1  1  1  1  1  1 -1  1 -1  1  1  1  1  1  1  1 -1 -1 -1  1 -1  1  1  1
 -1]
[[ 1  1 -1  1  1]
 [ 1  1 -1  1  1]
 [ 1  1 -1  1  1]
 [ 1 -1  1 -1  1]
 [-1 -1  1 -1 -1]]
[ 1  1 -1  1  1  1  1 -1  1  1  1  1 -1  1  1  1 -1  1 -1  1 -1 -1  1 -1
 -1]
Ursprüngliches Muster: [[ 1  1 -1  1  1]
 [ 1 -1 -1 -1  1]
 [ 1  1 -1  1  1]
 [ 1 -1 -1 -1  1]
 [-1  1  1  1 -1]]
Erkanntes Muster: [ 1  1  1  1  1  1 -1  1 -1  1  1  1  1  1  1  1 -1 -1 -1  1 -1  1  1  1
 -1]
Energie des erkannten Musters: -13.12


In [15]:

def capture_image():
    # Open the webcam (0 is the default device)
    cap = cv2.VideoCapture(0)
    if not cap.isOpened():
        print("Error: Could not open webcam")
        return None

    # Capture a single frame
    ret, frame = cap.read()
    cap.release()
    
    if not ret:
        print("Error: Could not capture image")
        return None

    # Convert the image to grayscale
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    return gray

def crop_center(image, crop_size):
    """
    Schneidet einen zentralen Ausschnitt aus einem Bild.

    Parameters:
    image (numpy.ndarray): Das Eingabebild als NumPy-Array.
    crop_size (int): Die Größe des quadratischen Ausschnitts.

    Returns:
    numpy.ndarray: Der zentrale Ausschnitt des Bildes.
    """
    h, w = image.shape
    startx = w // 2 - (crop_size // 2)
    starty = h // 2 - (crop_size // 2)
    return image[starty:starty + crop_size, startx:startx + crop_size]

def flip_values(matrix, probability):
    """
    Dreht die Werte in einer Matrix mit einer bestimmten Wahrscheinlichkeit um.

    Parameters:
    matrix (numpy.ndarray): Die Eingabematrix mit Werten -1 und 1.
    probability (float): Die Wahrscheinlichkeit, mit der die Werte umgedreht werden.

    Returns:
    numpy.ndarray: Die Matrix mit umgedrehten Werten basierend auf der gegebenen Wahrscheinlichkeit.
    """
    flip_mask = np.random.rand(*matrix.shape) < probability
    matrix[flip_mask] *= -1
    return matrix

# Capture an image from the webcam
gray_image = capture_image()

fig, axs = plt.subplots(2, network.steps, figsize=(12, 12))

if gray_image is not None:
    img = crop_center(gray_image,700)
    img = np.array(cv2.resize(img, (5,5)))
    mean = np.mean(img)
    img = np.where( img >= mean, 1, -1)
    axs[0,0].imshow(img)
    axs[0,0].set_title('Aufgenommenes Bild')
else:
    print("No image captured.")


noise_level = 0.001
noise_img = flip_values(img,0.1)
axs[0,1].imshow(noise_img)
axs[0,1].set_title(f'Bild mit Einem Noislevel von {noise_level*100}% ')
#Netzwerk Anwenden

network = HopfieldNetwork(num_neurons= 25, steps= 5)
steps = network.steps
network.train([img])
result = network.predict(noise_img,heviside, number_of_pattern= 2, axs=axs)
#matrix_result = network.show_as_matrix(result)
#axs[2].imshow(matrix_result)
for i in range(steps):
        if not axs[0, i].images:
            fig.delaxes(axs[0, i])

fig.tight_layout()
plt.show()
print(network.weights)



[[-1  1 -1  1 -1]
 [-1 -1  1  1  1]
 [-1 -1 -1  1 -1]
 [-1 -1  1 -1 -1]
 [-1 -1 -1 -1 -1]]
[-1  1 -1  1 -1 -1 -1  1  1  1 -1 -1 -1  1 -1 -1 -1  1 -1 -1 -1 -1 -1 -1
 -1]
[[ 0.   -0.04  0.04 -0.04  0.04  0.04  0.04 -0.04 -0.04 -0.04  0.04  0.04
   0.04 -0.04  0.04  0.04  0.04 -0.04  0.04  0.04  0.04  0.04  0.04  0.04
   0.04]
 [-0.04  0.   -0.04  0.04 -0.04 -0.04 -0.04  0.04  0.04  0.04 -0.04 -0.04
  -0.04  0.04 -0.04 -0.04 -0.04  0.04 -0.04 -0.04 -0.04 -0.04 -0.04 -0.04
  -0.04]
 [ 0.04 -0.04  0.   -0.04  0.04  0.04  0.04 -0.04 -0.04 -0.04  0.04  0.04
   0.04 -0.04  0.04  0.04  0.04 -0.04  0.04  0.04  0.04  0.04  0.04  0.04
   0.04]
 [-0.04  0.04 -0.04  0.   -0.04 -0.04 -0.04  0.04  0.04  0.04 -0.04 -0.04
  -0.04  0.04 -0.04 -0.04 -0.04  0.04 -0.04 -0.04 -0.04 -0.04 -0.04 -0.04
  -0.04]
 [ 0.04 -0.04  0.04 -0.04  0.    0.04  0.04 -0.04 -0.04 -0.04  0.04  0.04
   0.04 -0.04  0.04  0.04  0.04 -0.04  0.04  0.04  0.04  0.04  0.04  0.04
   0.04]
 [ 0.04 -0.04  0.04 -0.04  0.04  0.    0.04 -0